yarnPath: .yarn/releases/yarn-3.4.1.cjs

# https://yarnpkg.com/configuration/yarnrc/#nmHoistingLimits
nmHoistingLimits: none

# https://yarnpkg.com/configuration/yarnrc/#nmMode
nmMode: hardlinks-local

# This will cause Yarn to install the project just like Yarn 1 used to,
# by copying the packages into various node_modules folders.
# Support for yarn pnp will come later: https://github.com/nuxt/framework/issues/581
nodeLinker: node-modules
# nodeLinker: pnp
# pnpMode: loose

npmScopes:
  shopify:
    npmRegistryServer: 'https://registry.npmjs.com/'
