name: 'ci'
on:
  push:

jobs:
  typecheck:
    name: Typecheck
    # https://github.com/microsoft/playwright/issues/34342
    runs-on: ubuntu-22.04
    timeout-minutes: 15
    env:
      GH_PACKAGE_REGISTRY_TOKEN: ${{ secrets.GH_PACKAGE_REGISTRY_TOKEN }}
    concurrency:
      group: ci-typecheck-${{ github.ref }}
      cancel-in-progress: true
    steps:
      - name: ⬇️ Checkout repo
        uses: actions/checkout@v4

      - name: ⎔ Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 24
          cache: 'yarn'

      - name: 📥 Install dependencies
        run: yarn

      - name: 📦 Build packages
        run: yarn build

      - name: 👕 Lint
        run: yarn lint

      - name: 🔖 Typecheck
        run: yarn typecheck

      - name: 📥 Install Playwright Browsers
        run: npx playwright install --with-deps

      - name: 🎭 Playwright Tests
        run: yarn test
